# Lenovo Yoga 920-13IKB.
# Identisch zum Image-Default -- hier nur als Beispiel, wie eine
# maschinenspezifische Abweichung aussieht. Kann geloescht werden.

input "type:keyboard" {
    xkb_layout de
    xkb_variant nodeadkeys
    xkb_options terminate:ctrl_alt_bksp
}

# Yoga-Touchpad
input "type:touchpad" {
    tap enabled
    natural_scroll enabled
    dwt enabled
}
